services:
  user_db:
    image: postgres:14
    container_name: user_db
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: ./user_service
    container_name: user_service
    environment:
      - USER_DB_URL=postgresql://user:password@user_db:5432/users_db
    depends_on:
      user_db:
        condition: service_healthy
    ports:
      - "8001:8001"

  posts_db:
    image: postgres:14
    container_name: posts_db
    environment:
      - POSTGRES_DB=posts_db
      - POSTGRES_USER=posts_user
      - POSTGRES_PASSWORD=posts_password
    ports:
      - "5533:5432"
    volumes:
      - posts_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U posts_user -d posts_db" ]
      interval: 10s
      timeout: 5s
      retries: 5


  posts_service:
    build: ./posts_comments_service
    container_name: posts_service
    environment:
      - POSTS_DB_URL=postgresql://posts_user:posts_password@posts_db:5432/posts_db
    depends_on:
      posts_db:
        condition: service_healthy
      kafka:
        condition: service_healthy

    ports:
      - "50051:50051"

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    depends_on:
      user_service:
        condition: service_started
      posts_service:
        condition: service_started
      stats_service:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - USER_SERVICE_URL=http://user_service:8001
      - POSTS_SERVICE_ADDRESS=posts_service:50051
      - STATS_SERVICE_ADDRESS=stats_service:50050
      - JWT_SECRET_KEY=SUPER_SECRET_KEY
    ports:
      - "8000:8000"
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - default
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
      interval: 2s
      timeout: 2s
      retries: 25

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPERS=
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
    links:
      - kafka
    networks:
      - default

  stats_clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - stats_clickhouse_data:/var/lib/clickhouse
      - ./stats_clickhouse/init:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_DB=stats_db
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_SETTINGS_stream_like_engine_allow_direct_select=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 3s
      retries: 10

  stats_service:
    build: ./stats_service
    container_name: stats_service
    depends_on:
      stats_clickhouse:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - CLICKHOUSE_USER_NAME=default
      - CLICKHOUSE_DATABASE=stats_db
      - CLICKHOUSE_PASSWORD=clickhouse

    ports:
      - "50050:50050"

volumes:
  user_db_data:
  posts_db_data:
  kafka_data:
  stats_clickhouse_data:

networks:
  default:
    driver: bridge
